# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grpcmd < Formula
  desc "A simple, easy-to-use, and developer-friendly CLI tool for gRPC."
  homepage "https://github.com/grpcmd/grpcmd"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.1/grpcmd_0.1.1_darwin_arm64.tar.gz"
      sha256 "0e24a49c1535dec50152ca615301e4aa7b83b62f8b791de6ac876a437b4bb96a"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.1/grpcmd_0.1.1_darwin_amd64.tar.gz"
      sha256 "601c355a97c30cbf9c5f638c8388e5a21ccde65ad3d76d301a853f5249db815e"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.1/grpcmd_0.1.1_linux_amd64.tar.gz"
      sha256 "16fb2d92a3da427e3a95cb4b8d0879c0f5106783c76e2d5ab959e7b6c7ebe437"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.1/grpcmd_0.1.1_linux_arm64.tar.gz"
      sha256 "84ebb99adc54ca3f39a26fbd0bef1c213edfd6d3eb1d7f74a97f866b03295a67"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
  end
end
