# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grpcmd < Formula
  desc "A simple, easy-to-use, and developer-friendly CLI tool for gRPC."
  homepage "https://github.com/grpcmd/grpcmd"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.2/grpcmd_0.1.2_darwin_amd64.tar.gz"
      sha256 "639fbf0ec1c76251fe1cfe2e3b5f8cee2cb15e8439a13af46547f5d6de41a465"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.2/grpcmd_0.1.2_darwin_arm64.tar.gz"
      sha256 "1e843cc7b990ec857961c2e8610a0cc6d53e62abe3de0b730ae5c9390a838be1"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.2/grpcmd_0.1.2_linux_arm64.tar.gz"
      sha256 "d9209fe54476e6f210de556aee37992272444f58447ab7f49efd0111a90dd7d3"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.1.2/grpcmd_0.1.2_linux_amd64.tar.gz"
      sha256 "afa523e3ddd01767f983ef1200cf90af26d490cd9c6bb63c3c327904fe6f724e"

      def install
        bin.install "grpc"
        (bash_completion/"grpc").write `#{bin}/grpc completion bash`
        (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
        (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`
      end
    end
  end
end
