# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grpcmd < Formula
  desc ""
  homepage "https://github.com/grpcmd/grpcmd"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.0.2/grpcmd_0.0.2_darwin_amd64.tar.gz"
      sha256 "cfe1fca361b182967cfb355e9dc3a2bdfd42319d3f57bbae3ed972e89ceef9c4"

      def install
        bin.install "grpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.0.2/grpcmd_0.0.2_darwin_arm64.tar.gz"
      sha256 "82c1e1e72fae9fdd2d9d934c593a441f48e9053e311449d343ef3b1b1b8b3efe"

      def install
        bin.install "grpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.0.2/grpcmd_0.0.2_linux_arm64.tar.gz"
      sha256 "3232a43f1a401e01d6ab58cb7c2d3940377113207c191b9419830bb3ec6d27fa"

      def install
        bin.install "grpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grpcmd/grpcmd/releases/download/v0.0.2/grpcmd_0.0.2_linux_amd64.tar.gz"
      sha256 "ff201935878f167daf305c897e92997b43a8f176cbf1dfac411e6301a6c53dfa"

      def install
        bin.install "grpc"
      end
    end
  end
end
